FROM python:3.10-slim

WORKDIR /arewetoxic

ARG GCP_SERVICE_ACCOUNT

ENV GOOGLE_APPLICATION_CREDENTIALS=${GCP_SERVICE_ACCOUNT}

COPY ${GCP_SERVICE_ACCOUNT} ${GCP_SERVICE_ACCOUNT}

RUN pip install --no-cache-dir google-cloud-storage google-cloud

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "scripts/dataset_processing.py"]