# Slang dictionary for text preprocessing
slang_dict = {
    'u': 'you',
    'r': 'are',
    'ur': 'your',
    'urs': 'yours',
    'youre': 'you are',
    'im': 'i am',
    'dont': 'do not',
    'cant': 'cannot',
    "can't": 'cannot',
    'wont': 'will not',
    'isnt': 'is not',
    'aint': 'is not',
    'arent': 'are not',
    'wasnt': 'was not',
    "wasn't": 'was not',
    'werent': 'were not',
    'havent': 'have not',
    "haven't": 'have not',
    'hasnt': 'has not',
    "hasn't": 'has not',
    'hadnt': 'had not',
    "hadn't": 'had not',
    'shouldnt': 'should not',
    "shouldn't": 'should not',
    'wouldnt': 'would not',
    "wouldn't": 'would not',
    'couldnt': 'could not',
    "couldn't": 'could not',
    'dont': 'do not',
    "don't": 'do not',
    'doesnt': 'do not',
    'didnt': 'did not',
    "didn't": 'did not',
    'ill': 'i will',
    "i'll": 'i will',
    'id': 'i would',
    "i'd": 'i would',
    'ive': 'i have',
    'idk': "i do not know",
    'ikr': "i know right",
    'tbh': "to be honest",
    'brb': "be right back",
    'btw': "by the way",
    'omg': "oh my god",
    'lmk': "let me know",
    'smh': "shaking my head",
    'tho': "though",
    'thru': "through",
    'yall': "you all",
    'gonna': "going to",
    'wanna': "want to",
    'gotta': "got to",
    'lemme': "let me",
    'kinda': "kind of",
    'sorta': "sort of",
    'whatcha': "what are you",
    'dunno': "do not know",
    'nvm': "never mind",
    'pls': "please",
    'plz': "please",
    'cuz': "because",
    'cos': "because",
    'bc': "because",
    'w/e': "whatever",
    'w/o': "without",
    'b/c': "because",
    'bday': "birthday",
    'gr8': "great",
    'l8r': "later",
    'yolo': "you only live once",
    'fyi': "for your information",
    'np': "no problem",
    'ty': "thank you",
    'thx': "thanks",
    'msg': "message",
    'bcuz': "because",
    'ttyl': "talk to you later",
    'omw': "on my way",
    'jk': "just kidding",
    'b4': "before",
    'cya': "see you",
    'asap': "as soon as possible",
    'pic': "picture",
    'pics': "pictures",
    'prolly': "probably",
    'rly': "really",
    'srsly': "seriously",
    'luv': "love",
    'ya': "you",
    'nite': "night",
    'tmrw': "tomorrow",
    'btwn': "between",
    'thx': "thanks",
    'fwd': "forward",
    'bbl': "be back later",
    'gg': "good game",
    'imo': "in my opinion",
    'imho': "in my humble opinion",
    'irl': "in real life",
    'ftw': "for the win",
    'afk': "away from keyboard",
    'rofl': "rolling on the floor laughing",
    'lol': "laughing out loud",
    'ppl': "people",
    'fam': "family",
    'dm': "direct message",
    'bc': "because",
    'wud': "what would",
    'wyd': "what are you doing",
    'l8': "late",
    'fomo': "fear of missing out",
    'hmu': "hit me up",
    'rn': "right now",
    'yo': "hello",
    'birches': "bitches",
    'birch' : 'bitch',
    'fknu' : 'fuck',
    'abso': 'absolute',
    'absurdz': 'absurd',
    'azz': 'ass',
    'b1tch': 'bitch',
    'biatch': 'bitch',
    'bish': 'bitch',
    'btch': 'bitch',
    'bih': 'bitch',
    'bltch': 'bitch',
    'bitchz': 'bitch',
    'bustard': 'bastard',
    'bullshyt': 'bullshit',
    'ch1nk': 'chink',
    'c0ck': 'cock',
    'cr@p': 'crap',
    'cruddy': 'crap',
    'cuk': 'cuck',
    'cnt': 'cunt',
    'cum': 'come',
    'cvm': 'come',
    'clt': 'clit',
    'cl1t': 'clit',
    'cuntz': 'cunt',
    'd1ck': 'dick',
    'dik': 'dick',
    'dikk': 'dick',
    'dumbass': 'dumb ass',
    'dumba$$': 'dumb ass',
    'dumass': 'dumb ass',
    'effin': 'fucking',
    'f***': 'fuck',
    'f**k': 'fuck',
    'f*ck': 'fuck',
    'fuk': 'fuck',
    'fk': 'fuck',
    'fkr': 'fucker',
    'fukk': 'fuck',
    'frck': 'frick',
    'freakin': 'fucking',
    'freakn': 'fucking',
    'frckn': 'fucking',
    'f4g': 'fag',
    'f4ggot': 'faggot',
    'fa99ot': 'faggot',
    'fuq': 'fuck',
    'fvck': 'fuck',
    'g@y': 'gay',
    'ghey': 'gay',
    'gayz': 'gay',
    'gaybo': 'gay',
    'hoar': 'whore',
    'ho3': 'hoe',
    'h0e': 'hoe',
    'h0r': 'whore',
    'idiotz': 'idiot',
    'id10t': 'idiot',
    'jackass': 'jerk',
    'k1ll': 'kill',
    'kys': 'kill yourself',
    'kl0wn': 'clown',
    'klwn': 'clown',
    'loserz': 'loser',
    'luser': 'loser',
    'l00ser': 'loser',
    'lmfao': 'laughing my fucking ass off',
    'moronz': 'moron',
    'm0ron': 'moron',
    'mofo': 'motherfucker',
    'motherfkr': 'motherfucker',
    'motherfvcker': 'motherfucker',
    'mthrfkr': 'motherfucker',
    'n00b': 'newbie',
    'nob': 'noob',
    'nibba': 'nigger',
    'ni99a': 'nigger',
    'niqqa': 'nigger',
    'p0rn': 'porn',
    'p0ssy': 'pussy',
    'prck': 'prick',
    'pussi': 'pussy',
    'puzzy': 'pussy',
    'rap3': 'rape',
    'retardz': 'retard',
    'rtard': 'retard',
    'schmuck': 'jerk',
    'sh1t': 'shit',
    'sht': 'shit',
    'sh!t': 'shit',
    'shyt': 'shit',
    'shtty': 'shitty',
    'suckz': 'sucks',
    'sucka': 'sucker',
    'sukk': 'suck',
    'suks': 'sucks',
    'sukr': 'sucker',
    'slutty': 'slut',
    'skank': 'prostitute',
    'th0t': 'thot',
    't1tty': 'titty',
    'tw@t': 'twat',
    'twat': 'twit',
    'vgn': 'virgin',
    'wh0re': 'whore',
    'wtf': 'what the fuck',
    'wtfh': 'what the fuck',
    'y0': 'you',
    'yeet': 'throw',
    'yoosuck': 'you suck',
    'yousuk': 'you suck'
}